### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by dariodip** [balena-os/librsync-go#4]
Is this repository still active?

**Comment by lmbarros** [comment]
Hi! At balena we use this library in production and have been using it for years. It's definitely not abandoned. It has seen a long period without updates because it was doing everything we needed. Right now we are going through a cycle of improvements on the library, especially with regards to testing and hopefully some performance improvements.

So, yes, this is active in a certain way, but I'd say its pretty much feature complete (for our purposes at least), which explains these long periods without updates.
